### ISSUE TITLE
Bug: Refreshing the page during Symptom input breaks the app functionallity

### ISSUE THREAD

**Issue by guillemgarciagomez** [alexanderjaye/remedic-app#192]
If the user refreshes the page during the different stages of entering the symptomps, the consultation id saved in the context is lost, causing an error when the patient tries to submit the symptomps.

From the user prespective it looks like the submit went fine (they get redirected to the chat) but the consultation is not created, so they will never be attended by the doctor.

**Comment by alexanderjaye** [comment]
Finished
