### ISSUE TITLE
In the doctor chat, the symptoms by are not in English

### ISSUE THREAD

**Issue by mpatel66** [alexanderjaye/remedic-app#215]
The symptoms by area either need to be translated to english (or the doctor's language), or they need to be stored in English in the DB.

See the screen shot below

<img width="422" alt="Remedic" src="https://user-images.githubusercontent.com/40766801/107127255-d14bc700-68ac-11eb-8d39-acd9b02a7267.png">

**Comment by alexanderjaye** [comment]
Solved, symptoms now have translation field

**Comment by alexanderjaye** [comment]
Finished
